kind: Pod
apiVersion: v1
metadata:
  name: env-test-1
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20hrs'


# kind: Pod
# apiVersion: v1
# metadata:
#   name: env-test1
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     env:
#     - name: course
#       value: 'kubernetes'
#     - name: duration
#       value: '20hours'