kind: Pod
apiVersion: v1
metadata:
  name: env-test
  labels:
    name: sravani
    course: devops
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: sravani
      value: devops
    - name: k8
      value: siva