kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
  # this is for all values 
    envFrom:
    - configMapRef:
        name: daws24

  # this will for more values
    # env:
    # - name: courseName
    #   valueFrom:
    #     configMapKeyRef:
    #       name: daws24
    #       key: course
    # - name: trainerName
    #   valueFrom:
    #     configMapKeyRef:
    #       name: daws24
    #       key: trainer

