kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  # these labels are deployment related
  labels:
    app: nginx
    tier: web
    purpose: deployment
# replicas 3
spec:
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
# pod definition
template:
  metadata:
    labels:
      app: nginx
      tier: web
      project: test-project
      extra-key: extra-value
  spec:
    containers:
    - name: nginx
      image: nginx

